name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python py3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install CI dependencies
        run: python -m poetry install
      - name: Use tox to run CI checks
        run: python -m poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
